general.import = [
    "./themes/themes/xterm.toml"
    # "./themes/themes/kimbie_dark.toml"
    # "./themes/themes/hyper.toml"
    # "./themes/themes/chicago95.toml"
    # "./themes/themes/blood_moon.toml"
]
[colors]
# draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#FFFFFF"
text = "#000000"


[env]
TERM = "xterm-256color"
# TERM: screen-256color

[font]
size = 14
# [font.normal]
# family= "Noto Sans"
normal.family= "MesloLGS Nerd Font Mono"
# style = "Regular"


[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 10000
# Scrolling distance multiplier.
multiplier = 3

[terminal.shell]
program= "/run/current-system/sw/bin/bash"
args = ["--login", "-c", "/home/dinesh/script/session.sh"]

[window]
 # opacity = 0.9
blur = true

# Square corners
decorations = "none"
# Round corners
# decorations = "buttonless"

[window.padding]
x = 3
y = 7

[window.dimensions]
columns = 185
lines = 40

# [window.position]
# x = 0
# y = 430

[selection]
save_to_clipboard = true
