set -g pane-base-index 1
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'akohlbecker/aw-watcher-tmux'

set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g history-limit 10000
set -g mouse on

unbind C-b
unbind-key -n C-l
# set-option -g prefix C-a #set the prefix = Ctrl+ a
set-option -g prefix C-i #Tak as prefix
bind C-i send-prefix

#splite panes
bind '/' split-window -h
bind ';' split-window -v

#showing_date_name_time
krfx="#{?client_prefix,<Prefix>,}"
set -g status-right "${prfx}"
set -g status-style 'bg=#333333 fg=#5eacd3'


#reload config
bind r source-file ~/.tmux.conf \; display "Reloaded the config by defalut"

#h hostshort , #S session , #W window , #T pane name
wg_prfx=" #[fg=colour231,bg=default]#{?client_prefix,<Prefix>,}"  # prefix indicator widget
wg_pane=" #[fg=colour202,bg=default]#{=26:pane_title}"
wg_date=" #[fg=colour231,bold,italics,bg=default]%d-%b-%Y#[none]"
wg_time=" #[fg=colour220,bold,bg=default]%H:%M"

set -g status-right "${wg_prfx}${wg_pane}${wg_date}${wg_time}"

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'


# switch windows alt+number
# bind -n M-1 select-window -t 1
# bind -n M-2 select-window -t 2
# bind -n M-3 select-window -t 3
# bind -n M-4 select-window -t 4

# Remap Alt + [,] to switch to the previous,next window
bind -n M-[ previous-window
bind -n M-] next-window

# kill window using j
bind-key j confirm-before -p "Kill window? (y/n)" kill-window

#prefix(c-a) + n for rename window
bind-key n command-prompt -p "Rename window: " "rename-window '%%'"

#c=> create new window

#s for rename session
bind s command-prompt -p "Rename session: " "rename-session '%%'"

#h for new session
bind-key h command-prompt -p "Enter session name: " "new-session -s '%%'"

#show session and window and switch

bind t display-popup -E -x 35 -y 25 "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | cat <(tmux display-message -p '#S') - | fzf --reverse | xargs tmux switch-client -t"
bind u display-popup -E -x 35 -y 25 "tmux list-windows | fzf --reverse --with-nth=2 --delimiter=':' | awk -F: '{print \$1}' | xargs -I{} tmux select-window -t {}"

# Set the length of the left status bar so that i can give more lentht to sessinName
set-option -g status-left-length 40

#forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

run-shell '~/.tmux/plugins/tpm/tpm'
