#This is plugins
set -g pane-base-index 1
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'akohlbecker/aw-watcher-tmux'

set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g history-limit 10000
set -g mouse on
set -g pane-border-status off

# Unbind the default prefix (C-b)
unbind C-b

# Set the prefix to Tab
set-option -g prefix Tab

# Bind Tab to send the prefix
bind Tab send-prefix
bind Tab send-prefix \; display "Prefix clicked"
bind r source-file ~/.tmux.conf \; display "tmux reloaded"

#splite panes
bind '/' split-window -h
bind ';' split-window -v

# vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


#enable vim mode
# bind v if-shell "[[ #{pane_in_mode} == 1 ]]" "send-keys -X cancel" "copy-mode -u"

# bind v if-shell -F '#{==:#{pane_current_command},vim} || #{==:#{pane_current_command},nvim}' \
#     "display-message 'Already in Vim!'" \
#     "if-shell '#{pane_in_mode}' 'send-keys -X cancel' 'copy-mode -u'"
# bind v if-shell -F "#{pane_in_mode}" "send-keys -X cancel" "copy-mode -u"
# bind i if-shell -F "#{pane_in_mode}" "send-keys -X cancel" "send-keys i"
# set-window-option -g mode-keys vi
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# bind -T copy-mode-vi Escape send-keys -X cancel


# Pressing 'v' in normal mode enters copy mode (Vim-like navigation mode)
bind v if-shell -F '#{pane_in_mode}' \
    'send-keys -X cancel' \
    'copy-mode -u'

bind -T copy-mode-vi p if-shell -F '#{pane_in_mode}' \
    'send-keys -X begin-selection' \
    'send-keys -X cancel'

# Vim-like keybindings in copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel
# Copy to system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"


# Remap Alt + [,] to switch to the previous,next window
bind -n M-[ previous-window
bind -n M-] next-window

# kill window using j
bind-key p confirm-before -p "Kill window? (y/n)" kill-window

#prefix(Tab) + n for rename window
bind-key i command-prompt -p "Rename window: " "rename-window '%%'"

#c=> create new window

#s for rename session
bind s command-prompt -p "Rename session: " "rename-session '%%'"

#h for new session
bind-key n command-prompt -p "Enter session name: " "new-session -s '%%'"

#show session and window and switch
bind t display-popup -E -x 35 -y 25 "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | cat <(tmux display-message -p '#S') - | fzf --reverse | xargs tmux switch-client -t"
bind u display-popup -E -x 35 -y 25 "tmux list-windows | fzf --reverse --with-nth=2 --delimiter=':' | awk -F: '{print \$1}' | xargs -I{} tmux select-window -t {}"

# Set the length of the left status bar so that i can give more lentht to sessinName
set-option -g status-left-length 40

#forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/script/tmux_sessionaizer.sh"

run-shell '~/.tmux/plugins/tpm/tpm'
